import { useState } from 'react';
import type { Shape } from 'plotly.js';
import { Chart } from '../../components/Chart';
import { DEFAULT_BOUNDS, intervalProbability, normalCdf, sampleCurve, validateBounds } from './logic';
const curve = sampleCurve();
const format = (value: number, digits = 4) => value.toLocaleString('de-DE', { minimumFractionDigits: digits, maximumFractionDigits: digits });
export default function NormalverteilungApp() {
  const [aText, setA] = useState(String(DEFAULT_BOUNDS.a));
  const [bText, setB] = useState(String(DEFAULT_BOUNDS.b));
  const a = aText.trim() === '' ? NaN : Number(aText);
  const b = bText.trim() === '' ? NaN : Number(bText);
  const error = validateBounds(a, b);
  const valid = !error;
  const pa = valid ? normalCdf(a) : 0;
  const pb = valid ? normalCdf(b) : 0;
  const area = valid ? sampleCurve(a,b) : { x: [], density: [], cdf: [] };
  const line = (x0: number, x1: number, y0: number, y1: number): Partial<Shape> => ({ type: 'line', x0, x1, y0, y1, line: { color: '#3c5968', dash: 'dash', width: 2 } });
  const guides = valid ? [line(a,a,0,pa),line(b,b,0,pb),line(-6,a,pa,pa),line(-6,b,pb,pb)] : [];
  return <><p className="eyebrow">Statistik · Z ∼ N(0, 1)</p><h1>Bereichs&shy;wahrscheinlichkeit unter der Standard&shy;normal&shy;verteilung</h1><details><summary>Hinweise zur Verwendung und Formeln</summary><p>Die Fläche unter der Dichte zwischen a und b entspricht der Wahrscheinlichkeit für ein Ergebnis in diesem Intervall. Z sowie seine Grenzen sind dimensionslos.</p><p className="formula">φ(z) = exp(−z²/2) / √(2π)</p><p className="formula">Φ(z) = ∫ von −∞ bis z φ(u) du</p><p className="formula">P(a ≤ Z ≤ b) = Φ(b) − Φ(a)</p><p>Die Zahlenfelder und die beiden Griffe des Bereichsschiebers steuern dieselben Grenzen. Die Standardnormalverteilung hat Mittelwert 0 und Standardabweichung 1.</p></details>
  <section className="controls" aria-label="Intervallgrenzen"><div className="input-grid"><label>Untere Grenze a<input type="number" min="-6" max="6" step="0.01" value={aText} onChange={e=>setA(e.target.value)} aria-invalid={!!error} aria-describedby={error ? 'bounds-error' : 'bounds-help'}/></label><label>Obere Grenze b<input type="number" min="-6" max="6" step="0.01" value={bText} onChange={e=>setB(e.target.value)} aria-invalid={!!error} aria-describedby={error ? 'bounds-error' : 'bounds-help'}/></label></div><p id="bounds-help">Wähle den Bereich [a, b] · Grenzen −6 bis 6 · Schrittweite 0,01</p><div className="range-group"><label htmlFor="range-a">Bereichsschieber: unterer Griff a</label><label htmlFor="range-b">Bereichsschieber: oberer Griff b</label><div className="range-track"><input id="range-a" type="range" min="-6" max="6" step="0.01" value={Number.isFinite(a)?a:0} onChange={e=>setA(e.target.value)}/><input id="range-b" type="range" min="-6" max="6" step="0.01" value={Number.isFinite(b)?b:0} onChange={e=>setB(e.target.value)}/></div></div>{error && <p id="bounds-error" className="error" role="alert">{error}</p>}</section>
  {valid && <section className="result" aria-live="polite" aria-label="Berechnungsergebnis"><strong>P({format(a,2)} ≤ Z ≤ {format(b,2)}) = {format(intervalProbability(a,b))}</strong><p>Φ({format(b,2)}) − Φ({format(a,2)}) = {format(pb)} − {format(pa)}</p><p>Bereichswahrscheinlichkeit: {format(intervalProbability(a,b)*100,2)} %</p></section>}
  <section className="charts" aria-label="Diagramme"><Chart title="Dichtefunktion" description="Markierte Fläche zwischen a und b; gestrichelte Linien kennzeichnen die Grenzen." data={[{ x: curve.x, y: curve.density, type: 'scatter', mode: 'lines', name: 'φ(z)', line: { color: '#164a87', width: 2 } },{ x: area.x, y: area.density, type: 'scatter', mode: 'lines', fill: 'tozeroy', name: 'Intervall [a, b]', fillcolor: 'rgba(0,112,83,0.25)', line: { color: '#007053' } }]} layout={{xaxis:{ title:{text:'z (dimensionslos)'},range:[-6,6]},yaxis:{title:{text:'Dichte φ(z)'}},showlegend:false,shapes:valid?[{...line(a,a,0,1),yref:'paper'},{...line(b,b,0,1),yref:'paper'}]:[]}}/>
  <Chart title="Verteilungsfunktion" description="Φ(a) und Φ(b) mit Hilfslinien; Wendepunkt bei z = 0 und Φ(0) = 0,5." data={[{x:curve.x,y:curve.cdf,type:'scatter',mode:'lines',name:'Φ(z)',line:{color:'#164a87',width:2}}, {x:valid?[a,b]:[],y:valid?[pa,pb]:[],type:'scatter',mode:'markers+text',text:valid?[format(pa),format(pb)]:[],textposition:valid?[pa>0.9?'bottom center':'top center',pb>0.9?'bottom center':'top center']:[],name:'Grenzwerte',marker:{color:'#007053',size:9}},{x:[0],y:[0.5],type:'scatter',mode:'markers',name:'Wendepunkt (0; 0,5)',marker:{color:'#164a87',symbol:'diamond',size:10}}]} layout={{xaxis:{title:{text:'z (dimensionslos)'},range:[-6,6]},yaxis:{title:{text:'Verteilungsfunktion Φ(z)'},range:[-0.05,1.05]},shapes:guides,showlegend:false}}/></section>
  <section className="feedback"><h2>Feedback & Support</h2><a href="https://github.com/dubbehendrik/lehrapps-web/issues/new?template=bug_report.yml" target="_blank" rel="noreferrer">Fehler melden</a><a href="https://github.com/dubbehendrik/lehrapps-web/issues/new?template=feature_request.yml" target="_blank" rel="noreferrer">Funktion anfragen</a></section><footer><strong>Disclaimer</strong><p>Diese Anwendung dient ausschließlich zu Demonstrations- und Lehrzwecken. Es wird keine Gewähr für die Richtigkeit, Vollständigkeit oder Aktualität der bereitgestellten Inhalte übernommen. Die Nutzung erfolgt auf eigene Verantwortung. Eine kommerzielle Verwendung ist ausdrücklich nicht gestattet. Für Schäden materieller oder ideeller Art, die durch die Nutzung der App entstehen, wird keine Haftung übernommen.</p><a href="mailto:hendrik.dubbe@hs-esslingen.de?subject=Anfrage%20zu%20Standardnormalverteilung-App">Prof. Dr.-Ing. Hendrik Dubbe</a></footer></>;
}
